name: Docker Build vttestserver
on:
  push:

permissions: read-all

jobs:
  build_and_push:
    name: Build and push vitess/vttestserver Docker images
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: true
      matrix:
        branch: [ mysql80 ]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Dockerfile path
        run: |
          echo "DOCKERFILE=./docker/vttestserver/Dockerfile.${{ matrix.branch }}" >> $GITHUB_ENV

      - name: Build and push on main
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: vitess/vttestserver:${{ matrix.branch }}

      - name: Get the Git tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set Docker tag name
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "DOCKER_TAG=vitess/vttestserver:${TAG_NAME}-${{ matrix.branch }}" >> $GITHUB_ENV

      - name: Build and push on tags
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: ${{ env.DOCKER_TAG }}